services:
  postgres:
    image: postgres:16-alpine
    container_name: health-tracker_dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-health_tracker}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      POSTGRES_SHARED_PRELOAD_LIBRARIES: "pg_stat_statements"
      # Security settings
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
      - ./docker/postgres/conf:/etc/postgresql/conf.d:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-health_tracker}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - health-tracker-network
    # Resource limits for production readiness
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

networks:
  health-tracker-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
